"""Change customers and sales

Revision ID: 57a9d1fba579
Revises: 0ce2169d97b3
Create Date: 2024-12-25 16:36:06.075478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a9d1fba579'
down_revision: Union[str, None] = '0ce2169d97b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'gender')
    # ### end Alembic commands ###
