"""Fix products

Revision ID: c237f24b7274
Revises: 4aaa9d6ad79b
Create Date: 2024-12-19 19:13:49.409424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c237f24b7274'
down_revision: Union[str, None] = '4aaa9d6ad79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_product_name_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_product_name_key', 'products', ['product_name'])
    # ### end Alembic commands ###
