"""Fixing ID's columns

Revision ID: fbe885161656
Revises: 57a9d1fba579
Create Date: 2024-12-25 20:18:32.798665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe885161656'
down_revision: Union[str, None] = '57a9d1fba579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('customers', 'customer_id')
    op.add_column('products', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('products', 'product_id')
    op.drop_constraint('saledetailss_product_id_fkey', 'saledetailss', type_='foreignkey')
    op.drop_constraint('saledetailss_sale_id_fkey', 'saledetailss', type_='foreignkey')
    op.create_foreign_key(None, 'saledetailss', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'saledetailss', 'sales', ['sale_id'], ['id'])
    op.add_column('sales', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('sales_customer_id_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'])
    op.drop_column('sales', 'sale_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sale_id', sa.INTEGER(), server_default=sa.text("nextval('sales_sale_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_customer_id_fkey', 'sales', 'customers', ['customer_id'], ['customer_id'])
    op.drop_column('sales', 'id')
    op.drop_constraint(None, 'saledetailss', type_='foreignkey')
    op.drop_constraint(None, 'saledetailss', type_='foreignkey')
    op.create_foreign_key('saledetailss_sale_id_fkey', 'saledetailss', 'sales', ['sale_id'], ['sale_id'])
    op.create_foreign_key('saledetailss_product_id_fkey', 'saledetailss', 'products', ['product_id'], ['product_id'])
    op.add_column('products', sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('products', 'id')
    op.add_column('customers', sa.Column('customer_id', sa.INTEGER(), server_default=sa.text("nextval('customers_customer_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_column('customers', 'id')
    # ### end Alembic commands ###
